kind: SwitchConfig
version: v1alpha1
refreshIndexAfter: 1h
kubeconfigStores:
- kind: filesystem
  id: default
  kubeconfigName: "*config"
  paths:
  - "~/.kubeconfigs"
- kind: gardener
  config:
    gardenerAPIKubeconfigPath: "~/.kubeconfigs/codesphere/gardener/config"
    landscapeName: "codesphere"
